[package]
name = "bare_api_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_builder = "0.20.2"
reqwest = { version = "0.13.1", default-features = false, features = ["form", "query", "rustls"] }
tokio = { version = "1.49.0", features = ["rt", "time"] }
